/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTransactionReference } from '../../models/api-response-transaction-reference';

export interface GetTransactionReferenceByReferenceNumber$Params {
  referenceNumber: string;
}

export function getTransactionReferenceByReferenceNumber(http: HttpClient, rootUrl: string, params: GetTransactionReferenceByReferenceNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTransactionReference>> {
  const rb = new RequestBuilder(rootUrl, getTransactionReferenceByReferenceNumber.PATH, 'get');
  if (params) {
    rb.path('referenceNumber', params.referenceNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTransactionReference>;
    })
  );
}

getTransactionReferenceByReferenceNumber.PATH = '/transaction-reference/{referenceNumber}';
