/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListBeneficiaryAiSuggestion } from '../../models/api-response-list-beneficiary-ai-suggestion';

export interface GetUserSuggestions$Params {
}

export function getUserSuggestions(http: HttpClient, rootUrl: string, params?: GetUserSuggestions$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListBeneficiaryAiSuggestion>> {
  const rb = new RequestBuilder(rootUrl, getUserSuggestions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListBeneficiaryAiSuggestion>;
    })
  );
}

getUserSuggestions.PATH = '/beneficiary/suggestions';
