[build]
  command = "npm run build:prod"
  publish = "dist/money-transfer"

[[plugins]]
  package = "./netlify-plugin-inject-env-vars"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200