/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseScheduledTransferResponseDto } from '../../models/api-response-scheduled-transfer-response-dto';

export interface CancelRecurringSeries$Params {
  parentId: number;
}

export function cancelRecurringSeries(http: HttpClient, rootUrl: string, params: CancelRecurringSeries$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseScheduledTransferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, cancelRecurringSeries.PATH, 'delete');
  if (params) {
    rb.path('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseScheduledTransferResponseDto>;
    })
  );
}

cancelRecurringSeries.PATH = '/scheduled-transfers/recurring/{parentId}';
