/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseScheduledTransferResponseDto } from '../../models/api-response-scheduled-transfer-response-dto';

export interface CancelTransfer$Params {
  id: number;
}

export function cancelTransfer(http: HttpClient, rootUrl: string, params: CancelTransfer$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseScheduledTransferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, cancelTransfer.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseScheduledTransferResponseDto>;
    })
  );
}

cancelTransfer.PATH = '/scheduled-transfers/{id}';
