/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePageResponseScheduledTransferResponseDto } from '../../models/api-response-page-response-scheduled-transfer-response-dto';

export interface GetUserTransfers$Params {
  page?: number;
  size?: number;
  sort?: Array<string>;
}

export function getUserTransfers(http: HttpClient, rootUrl: string, params?: GetUserTransfers$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePageResponseScheduledTransferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getUserTransfers.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sort', params.sort, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePageResponseScheduledTransferResponseDto>;
    })
  );
}

getUserTransfers.PATH = '/scheduled-transfers';
