/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseScheduledTransferResponseDto } from '../../models/api-response-scheduled-transfer-response-dto';
import { ScheduledTransferRequestDto } from '../../models/scheduled-transfer-request-dto';

export interface UpdateTransfer$Params {
  id: number;
      body: ScheduledTransferRequestDto
}

export function updateTransfer(http: HttpClient, rootUrl: string, params: UpdateTransfer$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseScheduledTransferResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateTransfer.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseScheduledTransferResponseDto>;
    })
  );
}

updateTransfer.PATH = '/scheduled-transfers/{id}';
