/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListPaymentMethod } from '../../models/api-response-list-payment-method';

export interface GetPaymentMethodsByCountryAcronym$Params {
  countryAcronym: string;
}

export function getPaymentMethodsByCountryAcronym(http: HttpClient, rootUrl: string, params: GetPaymentMethodsByCountryAcronym$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListPaymentMethod>> {
  const rb = new RequestBuilder(rootUrl, getPaymentMethodsByCountryAcronym.PATH, 'get');
  if (params) {
    rb.query('countryAcronym', params.countryAcronym, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListPaymentMethod>;
    })
  );
}

getPaymentMethodsByCountryAcronym.PATH = '/payment-methods/countryAcronym';
