/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUserBeneficiaryResponse } from '../../models/api-response-user-beneficiary-response';
import { UserBeneficiaryRequest } from '../../models/user-beneficiary-request';

export interface AddUserBeneficiary$Params {
      body: UserBeneficiaryRequest
}

export function addUserBeneficiary(http: HttpClient, rootUrl: string, params: AddUserBeneficiary$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUserBeneficiaryResponse>> {
  const rb = new RequestBuilder(rootUrl, addUserBeneficiary.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUserBeneficiaryResponse>;
    })
  );
}

addUserBeneficiary.PATH = '/beneficiaries/add';
