/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUserBeneficiaryResponse } from '../../models/api-response-user-beneficiary-response';

export interface GetUserBeneficiary$Params {
  beneficiaryId: number;
}

export function getUserBeneficiary(http: HttpClient, rootUrl: string, params: GetUserBeneficiary$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUserBeneficiaryResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserBeneficiary.PATH, 'get');
  if (params) {
    rb.path('beneficiaryId', params.beneficiaryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUserBeneficiaryResponse>;
    })
  );
}

getUserBeneficiary.PATH = '/beneficiaries/{beneficiaryId}';
