/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUserBeneficiariesResponse } from '../../models/api-response-user-beneficiaries-response';

export interface GetUserBeneficiaries$Params {
}

export function getUserBeneficiaries(http: HttpClient, rootUrl: string, params?: GetUserBeneficiaries$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUserBeneficiariesResponse>> {
  const rb = new RequestBuilder(rootUrl, getUserBeneficiaries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUserBeneficiariesResponse>;
    })
  );
}

getUserBeneficiaries.PATH = '/beneficiaries';
