/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountData {
  account_name?: string;
  account_number?: string;
  bank_id?: number;
}
