/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AccountLimitDto {
  dailyTransactionLimit?: number;
  formattedDailyLimit?: string;
  formattedMaxBalance?: string;
  formattedMaxDeposit?: string;
  formattedMaxTransfer?: string;
  formattedMaxWithdrawal?: string;
  maxDepositAmount?: number;
  maxTransferAmount?: number;
  maxWalletBalance?: number;
  maxWithdrawalAmount?: number;
  unlimited?: boolean;
  verificationLevel?: 'UNVERIFIED' | 'EMAIL_VERIFIED' | 'ID_VERIFIED' | 'FULLY_VERIFIED';
}
