/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddBankAccountRequest {
  bankAccountDetails?: {
};
  region?: 'AFRICA' | 'EU' | 'US';
}
