/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddBeneficiaryRequest {
  account_bank?: string;
  account_number?: string;
  beneficiary_name?: string;
}
