/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Admin {
  accountLocked?: boolean;
  adminId?: number;
  createdDate?: string;
  dateOfBirth?: string;
  email?: string;
  enabled?: boolean;
  firstName?: string;
  lastModifiedDate?: string;
  lastName?: string;
  password?: string;
  username?: string;
}
