/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountLimitDto } from '../models/account-limit-dto';
export interface ApiResponseAccountLimitDto {
  data?: AccountLimitDto;
  message?: string;
  success?: boolean;
}
