/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { KycVerification } from '../models/kyc-verification';
export interface ApiResponseKycVerification {
  data?: KycVerification;
  message?: string;
  success?: boolean;
}
