/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserBeneficiaryResponse } from '../models/user-beneficiary-response';
export interface ApiResponseUserBeneficiaryResponse {
  data?: UserBeneficiaryResponse;
  message?: string;
  success?: boolean;
}
