/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserBeneficiariesResponse } from '../models/user-beneficiaries-response';
export interface ApiResponseUserBeneficiariesResponse {
  data?: UserBeneficiariesResponse;
  message?: string;
  success?: boolean;
}
