/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionReference } from '../models/transaction-reference';
export interface ApiResponseTransactionReference {
  data?: TransactionReference;
  message?: string;
  success?: boolean;
}
