/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Wallet } from '../models/wallet';
export interface ApiResponseWallet {
  data?: Wallet;
  message?: string;
  success?: boolean;
}
