/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccount } from '../models/bank-account';
export interface ApiResponseBankAccount {
  data?: BankAccount;
  message?: string;
  success?: boolean;
}
