/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduledTransferResponseDto } from '../models/scheduled-transfer-response-dto';
export interface ApiResponseScheduledTransferResponseDto {
  data?: ScheduledTransferResponseDto;
  message?: string;
  success?: boolean;
}
