/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransferInitiationResponse } from '../models/transfer-initiation-response';
export interface ApiResponseTransferInitiationResponse {
  data?: TransferInitiationResponse;
  message?: string;
  success?: boolean;
}
