/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionFee } from '../models/transaction-fee';
export interface ApiResponseTransactionFee {
  data?: TransactionFee;
  message?: string;
  success?: boolean;
}
