/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PaymentMethod } from '../models/payment-method';
export interface ApiResponseListPaymentMethod {
  data?: Array<PaymentMethod>;
  message?: string;
  success?: boolean;
}
