/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Card } from '../models/card';
export interface ApiResponseCard {
  data?: Card;
  message?: string;
  success?: boolean;
}
