/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduledTransferResponseDto } from '../models/scheduled-transfer-response-dto';
export interface ApiResponseListScheduledTransferResponseDto {
  data?: Array<ScheduledTransferResponseDto>;
  message?: string;
  success?: boolean;
}
