/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MobileMoneyOption } from '../models/mobile-money-option';
export interface ApiResponseSetMobileMoneyOption {
  data?: Array<MobileMoneyOption>;
  message?: string;
  success?: boolean;
}
