/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TransactionResponse } from '../models/transaction-response';
export interface ApiResponseTransactionResponse {
  data?: TransactionResponse;
  message?: string;
  success?: boolean;
}
