/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PagedTransactionResponse } from '../models/paged-transaction-response';
export interface ApiResponsePagedTransactionResponse {
  data?: PagedTransactionResponse;
  message?: string;
  success?: boolean;
}
