/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduledTransferInitiationResponse } from '../models/scheduled-transfer-initiation-response';
export interface ApiResponseScheduledTransferInitiationResponse {
  data?: ScheduledTransferInitiationResponse;
  message?: string;
  success?: boolean;
}
