/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserNotificationPreferences } from '../models/user-notification-preferences';
export interface ApiResponseUserNotificationPreferences {
  data?: UserNotificationPreferences;
  message?: string;
  success?: boolean;
}
