/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiResponseMapStringMapStringObject {
  data?: {
[key: string]: {
[key: string]: {
};
};
};
  message?: string;
  success?: boolean;
}
