/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BeneficiaryAiSuggestion } from '../models/beneficiary-ai-suggestion';
export interface ApiResponseListBeneficiaryAiSuggestion {
  data?: Array<BeneficiaryAiSuggestion>;
  message?: string;
  success?: boolean;
}
