/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Admin } from '../models/admin';
export interface ApiResponseListAdmin {
  data?: Array<Admin>;
  message?: string;
  success?: boolean;
}
