/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRepresentation } from '../models/user-representation';
export interface ApiResponseUserRepresentation {
  data?: UserRepresentation;
  message?: string;
  success?: boolean;
}
