/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccount } from '../models/bank-account';
export interface ApiResponseListBankAccount {
  data?: Array<BankAccount>;
  message?: string;
  success?: boolean;
}
