/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageResponseScheduledTransferResponseDto } from '../models/page-response-scheduled-transfer-response-dto';
export interface ApiResponsePageResponseScheduledTransferResponseDto {
  data?: PageResponseScheduledTransferResponseDto;
  message?: string;
  success?: boolean;
}
