/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Card } from '../models/card';
export interface ApiResponseListCard {
  data?: Array<Card>;
  message?: string;
  success?: boolean;
}
