/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AccountData } from '../models/account-data';
export interface BankResolverResponse {
  data?: AccountData;
  message?: string;
  status?: boolean;
}
