/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Beneficiary {
  account_number?: string;
  bank_code?: string;
  bank_name?: string;
  created_at?: string;
  full_name?: string;
  id?: number;
}
