/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Card {
  cardName?: string;
  cardNumber?: string;
  cardType?: string;
  cvv?: string;
  expiryDate?: string;
  id?: number;
  locked?: boolean;
  pin?: string;
}
