/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTransactionRequestBody {
  amount?: number;
  narration?: string;
  receiverEmail?: string;
  senderEmail?: string;
}
