/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrencyData } from '../models/currency-data';
export interface ExchangeData {
  destination?: CurrencyData;
  rate?: number;
  source?: CurrencyData;
}
