/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExchangeData } from '../models/exchange-data';
export interface ExchangeRateResponse {
  data?: ExchangeData;
  message?: string;
  status?: string;
}
