/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
export interface FlaggedTransactionReason {
  id?: number;
  reason?: string;
  transaction?: Transaction;
}
