/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bank } from '../models/bank';
export interface FlutterwaveResponse {
  data?: Array<Bank>;
  message?: string;
  status?: string;
}
