/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WithdrawalMeta } from '../models/withdrawal-meta';
export interface FlutterwaveWithdrawalRequest {
  account_bank?: string;
  account_name?: string;
  account_number?: string;
  account_type?: string;
  amount?: number;
  bank_code?: string;
  bank_country?: string;
  bank_name?: string;
  beneficiary_address?: string;
  beneficiary_country?: string;
  beneficiary_name?: string;
  city?: string;
  currency?: string;
  meta?: Array<WithdrawalMeta>;
  narration?: string;
  postal_code?: string;
  reference?: string;
  region?: string;
  routing_number?: string;
  street_name?: string;
  street_number?: string;
  swift_code?: string;
}
