/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WithdrawalData } from '../models/withdrawal-data';
export interface GenericResponseWithdrawalData {
  data?: WithdrawalData;
  message?: string;
  status?: string;
}
