/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WithdrawalInitiationResponse } from '../models/withdrawal-initiation-response';
export interface GenericResponseWithdrawalInitiationResponse {
  data?: WithdrawalInitiationResponse;
  message?: string;
  status?: string;
}
