/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Beneficiary } from '../models/beneficiary';
export interface GenericResponseBeneficiary {
  data?: Beneficiary;
  message?: string;
  status?: string;
}
