/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeeData } from '../models/fee-data';
export interface GenericResponseListFeeData {
  data?: Array<FeeData>;
  message?: string;
  status?: string;
}
