/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduledTransferResponseDto } from '../models/scheduled-transfer-response-dto';
export interface PageResponseScheduledTransferResponseDto {
  content?: Array<ScheduledTransferResponseDto>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
