/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ScheduledTransferResponseDto {
  amount?: number;
  createdAt?: string;
  currentOccurrence?: number;
  description?: string;
  id?: number;
  isRecurring?: boolean;
  parentTransferId?: number;
  receiverEmail?: string;
  recurrenceEndDate?: string;
  recurrenceType?: 'NONE' | 'DAILY' | 'WEEKLY' | 'MONTHLY';
  scheduledDateTime?: string;
  senderEmail?: string;
  status?: 'PENDING' | 'EXECUTED' | 'PROCESSING' | 'FAILED' | 'CANCELLED';
  totalOccurrences?: number;
}
