/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponseDto {
  amount?: number;
  receiverName?: string;
  receiverWalletNumber?: string;
  referenceNumber?: string;
  senderName?: string;
  senderWalletNumber?: string;
  status?: string;
  transactionDate?: string;
  transactionType?: 'DEBIT' | 'CREDIT';
}
