/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TransactionResponse {
  amount?: number;
  currentStatus?: string;
  description?: string;
  fee?: number;
  flagged?: boolean;
  narration?: string;
  operation?: 'DEPOSIT' | 'WITHDRAWAL' | 'TRANSFER' | 'REVERSAL' | 'REFUND';
  providerId?: string;
  referenceNumber?: string;
  refundStatus?: 'PARTIALLY_REFUNDABLE' | 'FULLY_REFUNDABLE' | 'NON_REFUNDABLE';
  sessionId?: string;
  transactionDate?: string;
  transactionId?: number;
  transactionType?: 'DEBIT' | 'CREDIT';
  walletId?: string;
}
