/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Transaction } from '../models/transaction';
export interface TransactionReference {
  creditTransaction?: Transaction;
  debitTransaction?: Transaction;
  id?: number;
  referenceNumber?: string;
}
