/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserNotificationPreferencesRequest {
  notifyOnDeposit: boolean;
  notifyOnPaymentFailure: boolean;
  notifyOnReceive: boolean;
  notifyOnSend: boolean;
  notifyOnWithdraw: boolean;
}
