/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WithdrawalData } from '../models/withdrawal-data';
export interface WebhookPayload {
  data?: WithdrawalData;
  event?: string;
  'event.type'?: string;
}
