/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WithdrawalMeta {
  account_number?: string;
  bank_name?: string;
  beneficiary_address?: string;
  beneficiary_country?: string;
  beneficiary_name?: string;
  city?: string;
  email?: string;
  first_name?: string;
  last_name?: string;
  merchant_name?: string;
  mobile_number?: string;
  postal_code?: string;
  routing_number?: string;
  sender?: string;
  sender_country?: string;
  street_name?: string;
  street_number?: string;
  swift_code?: string;
}
