/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WithdrawalInfo } from '../models/withdrawal-info';
export interface WithdrawalRequestMapper {
  amount?: number;
  fee?: number;
  referenceNumber?: string;
  walletId?: string;
  withdrawalInfo?: WithdrawalInfo;
}
