/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WithdrawalData {
  account_number?: string;
  amount?: number;
  bank_code?: string;
  bank_name?: string;
  complete_message?: string;
  created_at?: string;
  currency?: string;
  fee?: number;
  full_name?: string;
  id?: number;
  is_approved?: number;
  narration?: string;
  reference?: string;
  requires_approval?: number;
  status?: string;
}
