/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BankAccount } from '../models/bank-account';
export interface WithdrawalInfo {
  amount?: number;
  bankAccount?: BankAccount;
  currency?: string;
  narration?: string;
}
