/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseWallet } from '../../models/api-response-wallet';

export interface GetWalletByUser$Params {
}

export function getWalletByUser(http: HttpClient, rootUrl: string, params?: GetWalletByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseWallet>> {
  const rb = new RequestBuilder(rootUrl, getWalletByUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseWallet>;
    })
  );
}

getWalletByUser.PATH = '/wallet';
