/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListTransactionResponse } from '../../models/api-response-list-transaction-response';

export interface GetTransactionByReferenceNumber$Params {
  referenceNumber: string;
}

export function getTransactionByReferenceNumber(http: HttpClient, rootUrl: string, params: GetTransactionByReferenceNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListTransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, getTransactionByReferenceNumber.PATH, 'get');
  if (params) {
    rb.path('referenceNumber', params.referenceNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListTransactionResponse>;
    })
  );
}

getTransactionByReferenceNumber.PATH = '/transactions/reference/{referenceNumber}';
