/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTransactionResponse } from '../../models/api-response-transaction-response';
import { UpdateTransactionRequest } from '../../models/update-transaction-request';

export interface UpdateTransactionStatus$Params {
  referenceNumber: string;
      body: UpdateTransactionRequest
}

export function updateTransactionStatus(http: HttpClient, rootUrl: string, params: UpdateTransactionStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTransactionResponse>> {
  const rb = new RequestBuilder(rootUrl, updateTransactionStatus.PATH, 'post');
  if (params) {
    rb.path('referenceNumber', params.referenceNumber, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTransactionResponse>;
    })
  );
}

updateTransactionStatus.PATH = '/transactions/status/{referenceNumber}';
