/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTransactionResponseDto } from '../../models/api-response-transaction-response-dto';
import { CreateTransactionRequestBody } from '../../models/create-transaction-request-body';

export interface SendMoney$Params {
      body: CreateTransactionRequestBody
}

export function sendMoney(http: HttpClient, rootUrl: string, params: SendMoney$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTransactionResponseDto>> {
  const rb = new RequestBuilder(rootUrl, sendMoney.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTransactionResponseDto>;
    })
  );
}

sendMoney.PATH = '/payment/send';
