/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseMapStringMapStringObject } from '../../models/api-response-map-string-map-string-object';

export interface GetCacheStats$Params {
}

export function getCacheStats(http: HttpClient, rootUrl: string, params?: GetCacheStats$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseMapStringMapStringObject>> {
  const rb = new RequestBuilder(rootUrl, getCacheStats.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseMapStringMapStringObject>;
    })
  );
}

getCacheStats.PATH = '/api/admin/cache/stats';
