/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseSetString } from '../../models/api-response-set-string';

export interface GetCacheKeys$Params {
  cacheName: string;
}

export function getCacheKeys(http: HttpClient, rootUrl: string, params: GetCacheKeys$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseSetString>> {
  const rb = new RequestBuilder(rootUrl, getCacheKeys.PATH, 'get');
  if (params) {
    rb.path('cacheName', params.cacheName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseSetString>;
    })
  );
}

getCacheKeys.PATH = '/api/admin/cache/{cacheName}/keys';
