/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListCard } from '../../models/api-response-list-card';

export interface FindCardByWalletId$Params {
  walletId: number;
}

export function findCardByWalletId(http: HttpClient, rootUrl: string, params: FindCardByWalletId$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListCard>> {
  const rb = new RequestBuilder(rootUrl, findCardByWalletId.PATH, 'get');
  if (params) {
    rb.path('walletId', params.walletId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListCard>;
    })
  );
}

findCardByWalletId.PATH = '/card/{walletId}';
