/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCard } from '../../models/api-response-card';
import { GenerateCardRequest } from '../../models/generate-card-request';

export interface GenerateCard$Params {
      body: GenerateCardRequest
}

export function generateCard(http: HttpClient, rootUrl: string, params: GenerateCard$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCard>> {
  const rb = new RequestBuilder(rootUrl, generateCard.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCard>;
    })
  );
}

generateCard.PATH = '/card/generate';
