/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseListBankAccount } from '../../models/api-response-list-bank-account';

export interface GetBankAccountsByUser$Params {
}

export function getBankAccountsByUser(http: HttpClient, rootUrl: string, params?: GetBankAccountsByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListBankAccount>> {
  const rb = new RequestBuilder(rootUrl, getBankAccountsByUser.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseListBankAccount>;
    })
  );
}

getBankAccountsByUser.PATH = '/bank-account';
