/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseUserNotificationPreferences } from '../../models/api-response-user-notification-preferences';
import { UserNotificationPreferencesRequest } from '../../models/user-notification-preferences-request';

export interface UpdateNotificationPreferences$Params {
      body: UserNotificationPreferencesRequest
}

export function updateNotificationPreferences(http: HttpClient, rootUrl: string, params: UpdateNotificationPreferences$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseUserNotificationPreferences>> {
  const rb = new RequestBuilder(rootUrl, updateNotificationPreferences.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseUserNotificationPreferences>;
    })
  );
}

updateNotificationPreferences.PATH = '/user-notification-preferences/update';
