/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseAccountLimitDto } from '../../models/api-response-account-limit-dto';

export interface GetMyAccountLimits$Params {
}

export function getMyAccountLimits(http: HttpClient, rootUrl: string, params?: GetMyAccountLimits$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseAccountLimitDto>> {
  const rb = new RequestBuilder(rootUrl, getMyAccountLimits.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseAccountLimitDto>;
    })
  );
}

getMyAccountLimits.PATH = '/api/account-limits/my-limits';
