/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseAccountLimitDto } from '../../models/api-response-account-limit-dto';

export interface GetLimitsForLevel$Params {
  level: 'UNVERIFIED' | 'EMAIL_VERIFIED' | 'ID_VERIFIED' | 'FULLY_VERIFIED';
}

export function getLimitsForLevel(http: HttpClient, rootUrl: string, params: GetLimitsForLevel$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseAccountLimitDto>> {
  const rb = new RequestBuilder(rootUrl, getLimitsForLevel.PATH, 'get');
  if (params) {
    rb.path('level', params.level, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseAccountLimitDto>;
    })
  );
}

getLimitsForLevel.PATH = '/api/account-limits/level/{level}';
