/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseVerificationLevel } from '../../models/api-response-verification-level';

export interface GetMyVerificationLevel$Params {
}

export function getMyVerificationLevel(http: HttpClient, rootUrl: string, params?: GetMyVerificationLevel$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseVerificationLevel>> {
  const rb = new RequestBuilder(rootUrl, getMyVerificationLevel.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseVerificationLevel>;
    })
  );
}

getMyVerificationLevel.PATH = '/account-limits/my-verification-level';
