/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccountLimitDto } from '../../models/account-limit-dto';
import { ApiResponseAccountLimitDto } from '../../models/api-response-account-limit-dto';

export interface UpdateLimitsForLevel$Params {
  level: 'UNVERIFIED' | 'EMAIL_VERIFIED' | 'ID_VERIFIED' | 'FULLY_VERIFIED';
      body: AccountLimitDto
}

export function updateLimitsForLevel(http: HttpClient, rootUrl: string, params: UpdateLimitsForLevel$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseAccountLimitDto>> {
  const rb = new RequestBuilder(rootUrl, updateLimitsForLevel.PATH, 'put');
  if (params) {
    rb.path('level', params.level, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseAccountLimitDto>;
    })
  );
}

updateLimitsForLevel.PATH = '/account-limits/level/{level}';
