/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenericResponseWithdrawalInitiationResponse } from '../../models/generic-response-withdrawal-initiation-response';
import { WithdrawalRequestMapper } from '../../models/withdrawal-request-mapper';

export interface InitiateWithdrawal$Params {
      body: WithdrawalRequestMapper
}

export function initiateWithdrawal(http: HttpClient, rootUrl: string, params: InitiateWithdrawal$Params, context?: HttpContext): Observable<StrictHttpResponse<GenericResponseWithdrawalInitiationResponse>> {
  const rb = new RequestBuilder(rootUrl, initiateWithdrawal.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenericResponseWithdrawalInitiationResponse>;
    })
  );
}

initiateWithdrawal.PATH = '/withdrawals/initiate';
