/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseKycVerification } from '../../models/api-response-kyc-verification';

export interface GetKycStatus$Params {
}

export function getKycStatus(http: HttpClient, rootUrl: string, params?: GetKycStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseKycVerification>> {
  const rb = new RequestBuilder(rootUrl, getKycStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseKycVerification>;
    })
  );
}

getKycStatus.PATH = '/kyc-verification/status';
