/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddBeneficiaryRequest } from '../../models/add-beneficiary-request';
import { GenericResponseBeneficiary } from '../../models/generic-response-beneficiary';

export interface AddBeneficiary$Params {
      body: AddBeneficiaryRequest
}

export function addBeneficiary(http: HttpClient, rootUrl: string, params: AddBeneficiary$Params, context?: HttpContext): Observable<StrictHttpResponse<GenericResponseBeneficiary>> {
  const rb = new RequestBuilder(rootUrl, addBeneficiary.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenericResponseBeneficiary>;
    })
  );
}

addBeneficiary.PATH = '/flutter/beneficiaries';
