/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GenericResponseListFeeData } from '../../models/generic-response-list-fee-data';

export interface GetFees$Params {
  amount: number;
  currency: string;
}

export function getFees(http: HttpClient, rootUrl: string, params: GetFees$Params, context?: HttpContext): Observable<StrictHttpResponse<GenericResponseListFeeData>> {
  const rb = new RequestBuilder(rootUrl, getFees.PATH, 'get');
  if (params) {
    rb.query('amount', params.amount, {});
    rb.query('currency', params.currency, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenericResponseListFeeData>;
    })
  );
}

getFees.PATH = '/flutter/fees';
