/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FlutterwaveResponse } from '../../models/flutterwave-response';

export interface GetBanks$Params {
  country: string;
}

export function getBanks(http: HttpClient, rootUrl: string, params: GetBanks$Params, context?: HttpContext): Observable<StrictHttpResponse<FlutterwaveResponse>> {
  const rb = new RequestBuilder(rootUrl, getBanks.PATH, 'get');
  if (params) {
    rb.path('country', params.country, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FlutterwaveResponse>;
    })
  );
}

getBanks.PATH = '/flutter/banks/{country}';
