/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ExchangeRateRequest } from '../../models/exchange-rate-request';
import { ExchangeRateResponse } from '../../models/exchange-rate-response';

export interface GetExchangeRate$Params {
  request: ExchangeRateRequest;
}

export function getExchangeRate(http: HttpClient, rootUrl: string, params: GetExchangeRate$Params, context?: HttpContext): Observable<StrictHttpResponse<ExchangeRateResponse>> {
  const rb = new RequestBuilder(rootUrl, getExchangeRate.PATH, 'get');
  if (params) {
    rb.query('request', params.request, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ExchangeRateResponse>;
    })
  );
}

getExchangeRate.PATH = '/flutter/rates';
