/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebhookPayload } from '../../models/webhook-payload';

export interface HandleWebhook1$Params {
  'verif-hash': string;
      body: WebhookPayload
}

export function handleWebhook1(http: HttpClient, rootUrl: string, params: HandleWebhook1$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, handleWebhook1.PATH, 'post');
  if (params) {
    rb.header('verif-hash', params['verif-hash'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

handleWebhook1.PATH = '/flutter/webhook';
