/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FlutterwaveWithdrawalRequest } from '../../models/flutterwave-withdrawal-request';
import { GenericResponseWithdrawalData } from '../../models/generic-response-withdrawal-data';

export interface Withdraw2$Params {
      body: FlutterwaveWithdrawalRequest
}

export function withdraw2(http: HttpClient, rootUrl: string, params: Withdraw2$Params, context?: HttpContext): Observable<StrictHttpResponse<GenericResponseWithdrawalData>> {
  const rb = new RequestBuilder(rootUrl, withdraw2.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GenericResponseWithdrawalData>;
    })
  );
}

withdraw2.PATH = '/flutter/withdraw';
