/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCountry } from '../../models/api-response-country';
import { CreateCountryRequestBody } from '../../models/create-country-request-body';

export interface AddNewCountry$Params {
      body: CreateCountryRequestBody
}

export function addNewCountry(http: HttpClient, rootUrl: string, params: AddNewCountry$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCountry>> {
  const rb = new RequestBuilder(rootUrl, addNewCountry.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCountry>;
    })
  );
}

addNewCountry.PATH = '/countries';
