/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCountry } from '../../models/api-response-country';

export interface GetCountryByName$Params {
  countryName: string;
}

export function getCountryByName(http: HttpClient, rootUrl: string, params: GetCountryByName$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCountry>> {
  const rb = new RequestBuilder(rootUrl, getCountryByName.PATH, 'get');
  if (params) {
    rb.path('countryName', params.countryName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCountry>;
    })
  );
}

getCountryByName.PATH = '/countries/{countryName}';
