/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseSetMobileMoneyOption } from '../../models/api-response-set-mobile-money-option';

export interface GetAllMobileMoneyOptions$Params {
  acronym: string;
}

export function getAllMobileMoneyOptions(http: HttpClient, rootUrl: string, params: GetAllMobileMoneyOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseSetMobileMoneyOption>> {
  const rb = new RequestBuilder(rootUrl, getAllMobileMoneyOptions.PATH, 'get');
  if (params) {
    rb.path('acronym', params.acronym, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseSetMobileMoneyOption>;
    })
  );
}

getAllMobileMoneyOptions.PATH = '/countries/mobile-money-options/{acronym}';
