/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseListAdmin } from '../models/api-response-list-admin';
import { getAllAdmins } from '../fn/admin-controller/get-all-admins';
import { GetAllAdmins$Params } from '../fn/admin-controller/get-all-admins';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllAdmins()` */
  static readonly GetAllAdminsPath = '/admin/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllAdmins()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAdmins$Response(params?: GetAllAdmins$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseListAdmin>> {
    return getAllAdmins(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllAdmins$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllAdmins(params?: GetAllAdmins$Params, context?: HttpContext): Observable<ApiResponseListAdmin> {
    return this.getAllAdmins$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseListAdmin>): ApiResponseListAdmin => r.body)
    );
  }

}
