/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseVoid } from '../models/api-response-void';
import { resendOtp } from '../fn/otp-controller/resend-otp';
import { ResendOtp$Params } from '../fn/otp-controller/resend-otp';

@Injectable({ providedIn: 'root' })
export class OtpControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `resendOtp()` */
  static readonly ResendOtpPath = '/otp/resend';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resendOtp()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resendOtp$Response(params: ResendOtp$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseVoid>> {
    return resendOtp(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resendOtp$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resendOtp(params: ResendOtp$Params, context?: HttpContext): Observable<ApiResponseVoid> {
    return this.resendOtp$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseVoid>): ApiResponseVoid => r.body)
    );
  }

}
