/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BankResolverResponse } from '../models/bank-resolver-response';
import { resolveBankAccount } from '../fn/pay-stack-controller/resolve-bank-account';
import { ResolveBankAccount$Params } from '../fn/pay-stack-controller/resolve-bank-account';

@Injectable({ providedIn: 'root' })
export class PayStackControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `resolveBankAccount()` */
  static readonly ResolveBankAccountPath = '/paystack/resolve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resolveBankAccount()` instead.
   *
   * This method doesn't expect any request body.
   */
  resolveBankAccount$Response(params: ResolveBankAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<BankResolverResponse>> {
    return resolveBankAccount(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resolveBankAccount$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  resolveBankAccount(params: ResolveBankAccount$Params, context?: HttpContext): Observable<BankResolverResponse> {
    return this.resolveBankAccount$Response(params, context).pipe(
      map((r: StrictHttpResponse<BankResolverResponse>): BankResolverResponse => r.body)
    );
  }

}
