/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { checkHealth } from '../fn/redis-health-controller/check-health';
import { CheckHealth$Params } from '../fn/redis-health-controller/check-health';
import { redisHealth } from '../fn/redis-health-controller/redis-health';
import { RedisHealth$Params } from '../fn/redis-health-controller/redis-health';

@Injectable({ providedIn: 'root' })
export class RedisHealthControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `checkHealth()` */
  static readonly CheckHealthPath = '/health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkHealth$Response(params?: CheckHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: {
};
}>> {
    return checkHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkHealth(params?: CheckHealth$Params, context?: HttpContext): Observable<{
[key: string]: {
};
}> {
    return this.checkHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: {
};
}>): {
[key: string]: {
};
} => r.body)
    );
  }

  /** Path part for operation `redisHealth()` */
  static readonly RedisHealthPath = '/health/redis';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `redisHealth()` instead.
   *
   * This method doesn't expect any request body.
   */
  redisHealth$Response(params?: RedisHealth$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: string;
}>> {
    return redisHealth(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `redisHealth$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  redisHealth(params?: RedisHealth$Params, context?: HttpContext): Observable<{
[key: string]: string;
}> {
    return this.redisHealth$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: string;
}>): {
[key: string]: string;
} => r.body)
    );
  }

}
