/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { generateStatement } from '../fn/statement-controller/generate-statement';
import { GenerateStatement$Params } from '../fn/statement-controller/generate-statement';

@Injectable({ providedIn: 'root' })
export class StatementControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `generateStatement()` */
  static readonly GenerateStatementPath = '/statements/generate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `generateStatement()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateStatement$Response(params: GenerateStatement$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return generateStatement(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `generateStatement$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  generateStatement(params: GenerateStatement$Params, context?: HttpContext): Observable<{
}> {
    return this.generateStatement$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
