/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseTransactionReference } from '../models/api-response-transaction-reference';
import { getTransactionReferenceByReferenceNumber } from '../fn/transaction-reference-controller/get-transaction-reference-by-reference-number';
import { GetTransactionReferenceByReferenceNumber$Params } from '../fn/transaction-reference-controller/get-transaction-reference-by-reference-number';

@Injectable({ providedIn: 'root' })
export class TransactionReferenceControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getTransactionReferenceByReferenceNumber()` */
  static readonly GetTransactionReferenceByReferenceNumberPath = '/transaction-reference/{referenceNumber}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTransactionReferenceByReferenceNumber()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransactionReferenceByReferenceNumber$Response(params: GetTransactionReferenceByReferenceNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTransactionReference>> {
    return getTransactionReferenceByReferenceNumber(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTransactionReferenceByReferenceNumber$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTransactionReferenceByReferenceNumber(params: GetTransactionReferenceByReferenceNumber$Params, context?: HttpContext): Observable<ApiResponseTransactionReference> {
    return this.getTransactionReferenceByReferenceNumber$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseTransactionReference>): ApiResponseTransactionReference => r.body)
    );
  }

}
