/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponseWallet } from '../models/api-response-wallet';
import { createWallet } from '../fn/wallet-controller/create-wallet';
import { CreateWallet$Params } from '../fn/wallet-controller/create-wallet';
import { getWalletByUser } from '../fn/wallet-controller/get-wallet-by-user';
import { GetWalletByUser$Params } from '../fn/wallet-controller/get-wallet-by-user';

@Injectable({ providedIn: 'root' })
export class WalletControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getWalletByUser()` */
  static readonly GetWalletByUserPath = '/wallet';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getWalletByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWalletByUser$Response(params?: GetWalletByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseWallet>> {
    return getWalletByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getWalletByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getWalletByUser(params?: GetWalletByUser$Params, context?: HttpContext): Observable<ApiResponseWallet> {
    return this.getWalletByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseWallet>): ApiResponseWallet => r.body)
    );
  }

  /** Path part for operation `createWallet()` */
  static readonly CreateWalletPath = '/wallet';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createWallet()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createWallet$Response(params: CreateWallet$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseWallet>> {
    return createWallet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createWallet$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createWallet(params: CreateWallet$Params, context?: HttpContext): Observable<ApiResponseWallet> {
    return this.createWallet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiResponseWallet>): ApiResponseWallet => r.body)
    );
  }

}
